import { Job, Company, User } from './types';

export const MOCK_USER: User = {
  name: 'Phuc',
  email: 'nguyenvanphuc3603@gmail.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Phuc',
  profileStrength: 75,
  isVerified: false,
};

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'google',
    name: 'Google',
    logo: 'https://www.gstatic.com/images/branding/product/1x/googleg_48dp.png',
    description: 'A global leader in technology, specializing in Internet-related services and products.',
    industry: 'Technology',
    location: 'Mountain View, CA',
    followers: 1200000,
  },
  {
    id: 'shopee',
    name: 'Shopee',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Shopee.svg/1200px-Shopee.svg.png',
    description: 'The leading e-commerce platform in Southeast Asia and Taiwan.',
    industry: 'E-commerce',
    location: 'Singapore',
    followers: 450000,
  },
  {
    id: 'fpt',
    name: 'FPT Software',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/FPT_logo.svg/1200px-FPT_logo.svg.png',
    description: 'A global software outsourcing and IT services company based in Vietnam.',
    industry: 'IT Services',
    location: 'Hanoi, Vietnam',
    followers: 85000,
  },
  {
    id: 'vng',
    name: 'VNG Corporation',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/VNG_logo.svg/1200px-VNG_logo.svg.png',
    description: 'A Vietnamese technology company, specializing in digital content and online entertainment.',
    industry: 'Technology',
    location: 'Ho Chi Minh City, Vietnam',
    followers: 62000,
  },
];

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    title: 'Senior Android Developer',
    company: 'Google',
    companyLogo: MOCK_COMPANIES[0].logo,
    location: 'Mountain View, CA (Remote)',
    salary: '$150k - $220k',
    type: 'Full-time',
    tags: ['Android', 'Kotlin', 'Jetpack Compose'],
    description: 'We are looking for an experienced Android Developer to join our core mobile team...',
    postedAt: '2 hours ago',
    isFeatured: true,
  },
  {
    id: '2',
    title: 'Backend Engineer (Node.js)',
    company: 'Shopee',
    companyLogo: MOCK_COMPANIES[1].logo,
    location: 'Ho Chi Minh City',
    salary: '$2,500 - $4,000',
    type: 'Full-time',
    tags: ['Node.js', 'PostgreSQL', 'Microservices'],
    description: 'Join Shopee to build high-performance backend systems for millions of users...',
    postedAt: '5 hours ago',
    isFeatured: true,
  },
  {
    id: '3',
    title: 'UI/UX Designer',
    company: 'VNG Corporation',
    companyLogo: MOCK_COMPANIES[3].logo,
    location: 'Ho Chi Minh City',
    salary: '$1,500 - $2,500',
    type: 'Full-time',
    tags: ['Figma', 'Material Design', 'Prototyping'],
    description: 'Create beautiful and functional interfaces for VNG\'s digital products...',
    postedAt: '1 day ago',
  },
  {
    id: '4',
    title: 'Frontend Developer (React)',
    company: 'FPT Software',
    companyLogo: MOCK_COMPANIES[2].logo,
    location: 'Hanoi',
    salary: '$1,200 - $2,000',
    type: 'Full-time',
    tags: ['React', 'TypeScript', 'Tailwind'],
    description: 'Work on international projects with the latest frontend technologies...',
    postedAt: '3 days ago',
  },
  {
    id: '5',
    title: 'Product Manager',
    company: 'Shopee',
    companyLogo: MOCK_COMPANIES[1].logo,
    location: 'Remote',
    salary: '$3,000 - $5,000',
    type: 'Remote',
    tags: ['Agile', 'Product Strategy', 'Analytics'],
    description: 'Drive the product vision and roadmap for Shopee\'s new features...',
    postedAt: '1 week ago',
  },
];
